name: Tool - Lint

on:
  workflow_call:
    inputs:
      checkout_ref:
        required: false
        type: string

jobs:
  lint:
    name: swiftlint
    runs-on: macos-14
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.checkout_ref || github.ref }}

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Run SwiftLint
        run: swiftlint lint --strict --reporter github-actions-logging
