name: pr

on:
  pull_request:

concurrency:
  group: pr-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    uses: ./.github/workflows/_tool_lint.yml

  test:
    uses: ./.github/workflows/_tool_test.yml

  build:
    needs: [lint, test]
    uses: ./.github/workflows/_tool_build.yml
